### ISSUE TITLE
Support for N-API

### ISSUE THREAD

**Issue by samvv** [neon-bindings/rfcs#27]
As discussed in [this issue](neon-bindings/neon#338), I propose making the change to the new N-API.

Supporting N-API has several benefits, the most important being that different node versions can use the same addon without recompiling. It will require some changes to the existing API, but my guess from experience with both projects is it will not be that bad.

**Comment by amilajack** [comment]
Adding N-API support is [already on the roadmap](https://neon-bindings.com/docs/roadmap). Also this RFC doesn't follow the RFC format. This seems to be more of a feature request.

**Comment by samvv** [comment]
Hi @amilajack thanks for the comment. I was going to file an RFC after running some experiments. Given that it is already on the roadmap, does that mean you already accept pull requests that would implement this?

**Comment by amilajack** [comment]
Yup, that's correct

**Comment by samvv** [comment]
@amilajack Oh, perfect! I'll give it a try, though I do not make any guarantees.

**Comment by anurbol** [comment]
Hi everyone. It seems to me that  the progress on switching to N-API has halted. Has it?

**Comment by kjvalencik** [comment]
@anurbol Nope! Some initial refactoring to allow development to occur on master with feature flags has already been merged. Some of the initial patters and implementation is being reviewed here: https://github.com/neon-bindings/neon/pull/458.

Unfortunately, progress can often be slower than we would like in an open source project primarily developed in the maintainers spare time.

**Comment by anurbol** [comment]
@kjvalencik Good to hear! Thanks! I totally understand why this may be slow. Actually I think open-source developers are heroes because I can't imagine myself spending **so much** effort on something that will not bring money. 

I'd love to help with that, but I think I will consume more time asking questions than actually help...

**Comment by kjvalencik** [comment]
If you'd like to help, we'd love to have it! There's a [quest issue](https://github.com/neon-bindings/neon/issues/444) soliciting help and providing some specific tasks that are up for grabs. We know it will be much faster with help from the community.

**Comment by anurbol** [comment]
@kjvalencik I wanted to ask if you have something like that quest, and you do indeed have it! Looks very nice and organized. I must say though, that in the last 2 hours I've dived into WASM as the alternative to the native binaries, I'll make a trial and see its performance, and if it's comparable to native Rust, then I'll have to go that way, otherwise I'll have to join you in implementing N-Api 😃 Thank you.

**Comment by kjvalencik** [comment]
Wasm is great and can be am excellent fit if it meets your use case (pure, no system access required). It's somewhat orthogonal to neon.

Wasi, on the other hand, more directly matches the neon use cases, but is very nascent.

**Comment by anurbol** [comment]
@kjvalencik Funny enough, it's exactly my case 😄  I am doing the files parsing and that's pretty much it, no OS stuff needed.. Thank you for insight!
